# Generated by Django 3.2.6 on 2021-09-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210911_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_of_product',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
