# Generated by Django 3.2.6 on 2021-09-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
